posts/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('create/',views.post_create,name='create'),
    path('all_posts/',views.posts,name='all_posts'),
    path('like',views.like_post,name='like'),
]

socialproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('users/',include('users.urls')),
    path('', include('users.urls')),
    path('posts/', include('posts.urls')),
    path('rooms/', include('chatapp.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users import views
from posts.views import edit_post
from django.contrib.auth import views as auth_view


# urlpatterns = [
#     path('',views.index, name='index'),
#     # path('login/',views.UserLogin.as_view(),name='login')
#     path('login/',views.user_login,name='login'),
#     # path('logout/',auth_view.LogoutView.as_view(template_name='users/logout.html'),name='logout')
#     path('logout/',views.user_logout,name='logout'),
#     path('password_change/',auth_view.PasswordChangeView.as_view(template_name='users/password_change.html'),name='change_password'),
#     path('password_change/done/',auth_view.PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'),name='password_change_done'),
#     path('password_reset/',auth_view.PasswordResetView.as_view(template_name='users/password_reset.html'),name='password_reset'),
#     path('password_reset/done/',auth_view.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),name='password_reset_done'),
#     path('reset/<uidb64>/<token>',auth_view.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),name='password_reset_confirm'),
#     path('password_reset_complete/',auth_view.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),name='password_reset_complete'),
#     path('register/',views.register,name='register'),
#     # path('register_done/',)
#     path('edit/',views.edit,name='edit'),
# ]

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.user_login, name='login'),
    path('users/<str:username>/', views.myView, name='userspage'),
    path('post/<int:post_id>/edit/', edit_post, name='edit_post'),
    path('logout/', auth_view.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password_change/', auth_view.PasswordChangeView.as_view(template_name='users/password_change_form.html'), name='password_change'),
    path('password_change/done/', auth_view.PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'), name='password_change_done'),
    path('password_reset/', auth_view.PasswordResetView.as_view(template_name= 'users/password_reset_form.html'), name = 'password_reset' ),
    path('password_reset/done/', auth_view.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>', auth_view.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name= 'password_reset_confirm'),
    path('reset/done/', auth_view.PasswordResetCompleteView.as_view(template_name = 'users/password_reset_complete.html'), name = 'password_reset_complete' ),
    path('register/', views.register, name='register'),
    path('edit/', views.edit, name='edit'),
    path('friendships/<str:username>/', views.FriendshipListView.as_view(), name='friends_list'),
    path('friendships/create/<int:user_id>/', views.CreateFriendshipView.as_view(), name='friends_create'),
    path('follows/<str:username>/', views.FollowersListView.as_view(), name='follower_list'),
    path('follows/create/', views.CreateFollowView.as_view(), name='follower_create'),
    path('about/', views.about_view, name='about'),
    ]

posts/models.py
from django.db import models
from django.conf import settings
from django.utils.text import slugify
from django.contrib.auth.models import User

# Create your models here.

class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    image = models.ImageField(default='users/images/post.png', upload_to='images/%y/%m/%d', blank=True)
    caption = models.TextField(blank=True)
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, blank=True)
    created = models.DateField(auto_now_add=True)
    liked_by = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='posts_liked', blank=True)

    def __str__(self):
        return self.title
    
    def save(self, *args, **kwargs):
        if not self.slug:
           self.slug = slugify(self.title)
        super().save(*args, **kwargs)


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    posted_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    body = models.CharField(max_length=200)
    created = models.DateField(auto_now_add=True)
    #modified = models.DateField(auto_now=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f"{self.posted_by.username}: {self.body}"
    # def __str__(self):
    #     return f"{self.user.username}: {self.body}"

class Message(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sent_messages')
    recipients = models.ManyToManyField(User, related_name='received_messages')
    subject = models.CharField(max_length=200)
    body = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.subject

users/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    photo = models.ImageField(default='users/images/anonymous.png', upload_to='users/%Y/%m/%d', blank=True)
    bio = models.TextField(max_length=200,blank=True)
    
    # phone_number=models.CharField(max_length=20,blank=True)
    # address=models.CharField(max_length=200,blank=True)
    # city=models.CharField(max_length=100,blank=True)
    # state=models.CharField(max_length=100,blank=True)
    # country=models.CharField(max_length=100,blank=True)
    # zip_code=models.CharField(max_length=10,blank=True)
    # created_at=models.DateTimeField(auto_now_add=True)
    # updated_at=models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.username
    

class Friendship(models.Model):
    from_user = models.ForeignKey(User, related_name='from_user', on_delete=models.CASCADE)
    to_user = models.ForeignKey(User, related_name='to_user', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        unique_together = ('from_user', 'to_user')

    def __str__(self):
        return f"{self.from_user} is friends with {self.to_user}"

class Follow(models.Model):
    from_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='follows_from')
    to_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='follows_to')
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('from_user', 'to_user')

    def __str__(self):
        return f"{self.from_user} follows {self.to_user}" 

users/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile, Friendship, Follow


class UserEditForm(forms.ModelForm):
    class Meta:
        model=User
        fields=('username', 'first_name', 'last_name', 'email')

class ProfileEditForm(forms.ModelForm):
    class Meta:
        model=Profile
        fields=('photo',) 


class LoginForm(forms.Form):
    username=forms.CharField()
    password=forms.CharField(widget=forms.PasswordInput)


class UserRegistrationForm(forms.ModelForm):
    password=forms.CharField(label='Password',widget=forms.PasswordInput)
    password2=forms.CharField(label='Confirm password',widget=forms.PasswordInput)
    profile_picture = forms.ImageField(required=False)
    class Meta:
        model=User
        fields={'username','email', 'profile_picture','first_name'}

    def check_password(self):
        cd = self.cleaned_data
        if cd["password"] != self.cleaned_data['password2']:
            raise forms.ValidationError('Passwords do not match')
        return cd['password2']
    

class FriendshipForm(forms.ModelForm):
    class Meta:
        model = Friendship
        fields = ('to_user',)

class FollowForm(forms.ModelForm):
    class Meta:
        model = Follow
        fields = ('to_user',)

users/views.py
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from .forms import LoginForm, UserRegistrationForm, FriendshipForm, FollowForm
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseForbidden, HttpResponseNotFound
from .models import Profile, Friendship, Follow, User
from .forms import UserEditForm, ProfileEditForm
from posts.forms import PostCreateForm
from posts.models import Post
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, CreateView, View
from django.db.models import F


# Create your views here.

#we should here talk about those new packages that we used them : login and authenticate 

def user_login(request):
    # here the type is POST so that means that we need to submit data and our reference here is forms.py

    if request.method =='POST':
        form=LoginForm(request.POST)
            # this one will be checked when we click submit because we configure it in the html file and set the submit method as POST 
        
        if form.is_valid():
            data=form.cleaned_data
            # cleaned_data only contains the data that has been validated by the form. This means that if a field in the form has a validation error, it will not be included in cleaned_data.

            user=authenticate(request,username=data['username'],password=data['password'])
            # The authenticate function checks if the provided username and password match a user in the database. If they do, it returns the user object. If they don't, it returns None.

            if user is not None:
                login(request,user)
                # The login function is a part of the authentication system. It is used to log a user in to create a session for the user.
                # return HttpResponse('user authenticated and logged in')
                return redirect(reverse('userspage', args=[user.username]))
            else:
                form.add_error(None, 'Invalid credentials')
    else:
        form= LoginForm()
    return render (request,'users/login.html',{'form':form})



def index(request):
    if request.user.is_authenticated:
        current_user = request.user
        posts = Post.objects.all().order_by('-created')
        profile = Profile.objects.all().first()
        return render(request, 'users/index.html', {'posts': posts, 'profile': profile})
    else:
        public_posts = Post.objects.all().order_by('-created')  # retrieve public posts
        return render(request, 'users/public_index.html', {'posts': public_posts})

def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        profile_form = ProfileEditForm(request.POST, request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.save()
            profile = profile_form.save(commit=False)
            profile.user = new_user
            profile.save()
            return render(request, 'users/register_done.html', {'new_user': new_user})
    else:
        user_form = UserRegistrationForm()
        profile_form = ProfileEditForm()
    return render(request, 'users/register.html', {'user_form': user_form, 'profile_form': profile_form})


# def register(request):
#     if request.method == 'POST':
#         user_form=UserRegistrationForm(request.POST)
#         if user_form.is_valid():
#             new_user=user_form.save(commit=False)
#             # it creates a new user object but doesn't save it to the database yet.
#             new_user.set_password(user_form.cleaned_data['password'])
#             new_user.save()
#             Profile.objects.create(user=new_user)
#             return render(request, 'users/register_done.html', {'new_user': new_user})
#     else:
#         user_form = UserRegistrationForm()
#     return render(request, 'users/register.html', {'user_form': user_form})   

@login_required
def edit(request):
    if request.method=='POST':
        user_form=UserEditForm(instance=request.user,data=request.POST)
        # instance parameter is used to specify the object that the form should update.
        profile_form=ProfileEditForm(instance=request.user.profile,data=request.POST,files=request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
    else:
        user_form=UserEditForm(instance=request.user)
        profile_form=ProfileEditForm(instance=request.user.profile)
    return render (request,'users/edit.html',{'user_form':user_form, 'profile_form':profile_form})


@login_required
def myView(request, username):
    current_user = request.user
    user = User.objects.get(username=username)
    if current_user != user:
        return HttpResponseForbidden()
    posts = Post.objects.filter(user=current_user).order_by('-created')
    profile = Profile.objects.filter(user=current_user).first()

    if request.method == 'POST':
        form = PostCreateForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = current_user
            post.save()
            return redirect('userspage',username=current_user.username)  # Redirect to the 'userspage' after saving the post
    else:
        form = PostCreateForm()

    return render(request, 'users/userspage.html', {'posts': posts, 'profile': profile, 'form': form})


class UserListView(ListView):
    model = User
    template_name = 'users/friends_create.html'
    context_object_name = 'users_with_profiles'
    
    def get_queryset(self):
        return User.objects.filter(profile__isnull=False)

class FriendshipListView(ListView):
    model = Friendship
    template_name = 'users/friends_list.html'
    context_object_name = 'friendships'

    def get_queryset(self):
        username = self.kwargs['username']
        self.user = User.objects.get(username=username)
        return Friendship.objects.filter(from_user=self.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = self.user
        return context


class CreateFriendshipView(LoginRequiredMixin, CreateView):
    model = Friendship
    form_class = FriendshipForm
    template_name = 'users/friends_create.html'
    success_url = reverse_lazy('friends_list')  # Redirect URL after successful form submission

    def form_valid(self, form):
        form.instance.from_user = self.request.user
        to_user = User.objects.get(id=self.kwargs['user_id'])
        form.instance.to_user = to_user
        return super().form_valid(form)
    # def form_valid(self, form):
    #     form.instance.from_user = self.request.user
    #     form.instance.to_user_id = self.kwargs['user_id']  # Set the `to_user` based on `user_id` from URL
    #     return super().form_valid(form)
    
class FriendsDeleteView(View):
    def post(self, request, id):
        try:
            user = User.objects.get(id=id)
            request.user.profile.friends.remove(user)
            return redirect('friends_list')
        except User.DoesNotExist:
            # Handle the case where the user is not found
            return HttpResponseNotFound('User not found')

        

class FollowersListView(ListView):
    model = Friendship
    template_name = 'users/follower_list.html'
    context_object_name = 'followers'

    def get_queryset(self):
        username = self.kwargs['username']
        self.user = User.objects.get(username=username)
        return Friendship.objects.filter(to_user=self.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = self.user
        context['users_with_profiles'] = User.objects.filter(profile__isnull=False)
        return context
    

class CreateFollowView(LoginRequiredMixin, CreateView):
    model = Follow
    form_class = FollowForm
    template_name = 'users/follower_create.html'

    def form_valid(self, form):
        form.instance.from_user = self.request.user
        return super().form_valid(form)

class FollowDeleteView(View):
    def post(self, request, id):
        try:
            user = User.objects.get(id=id)
            request.user.profile.follower.remove(user)
            return redirect('follower_list')
        except User.DoesNotExist:
            # Handle the case where the user is not found
            return HttpResponseNotFound('User not found')

def about_view(request):
    return render(request, 'users/about.html')

users/templates/users/base.html
{% load static %}
<html>
    <head>
        
        <link rel="stylesheet" href="{% static 'users/styles.css' %}">
        <link rel="stylesheet" href="{% static 'users/style.css' %}">
        <script src="https://code.jquery.com/jquery-3.7.1.js" integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous"></script>
        <title>{% block title %}    {% endblock %}</title>
    </head>
    <body>
        <nav class="shadow-lg">
            <div class="px-4 mx-auto">
                <div class="flex justify-between">
                    <div>
                        <a class="flex" href="{% url 'index' %}">
                            <img class="h-8 w-8 mr-2" src="{% static 'users/images/network_icon.png' %}" alt="">
                            <span class="font-semibold text-lg text-gray-500">CodeBreakers</span>
                        </a>
                    </div>
                    <div class="space-x-1">
                        {% if request.user.is_authenticated %}
                            <a class="py-4 px-2 text-gray-500 font-semibold" href="{% url 'userspage' username=request.user.username %}">Create Post</a>
                            <a class="py-4 px-2 text-gray-500 font-semibold" href="{% url 'feed' %}">All Posts</a>
                            <a class="py-4 px-2 text-gray-500 font-semibold" href="{% url 'chat_index' %}">Messages</a>
                            <a class="py-4 px-2 text-gray-500 font-semibold" href="{% url 'friends_list' username=request.user.username %}">Friends</a>
                            <a class="py-4 px-2 text-gray-500 font-semibold" href="{% url 'edit' %}">Edit</a>
                            <a class="py-4 px-2 text-gray-500 font-semibold" href="{% url 'about' %}">About Us</a>
                            <form id="logout-form" method="post" action="{% url 'logout' %}" style="display: inline;">
                                {% csrf_token %}
                                <button class="py-4 px-2 text-gray-500 font-semibold" type="submit">Logout</button>
                            </form>
                        {% else %}
                            <a class="py-4 px-2 text-gray-500 font-semibold" href="{% url 'index' %}">All Posts</a>
                            <a class="py-4 px-2 text-gray-500 font-semibold" href="{% url 'register' %}">Register</a>
                            <a class="py-4 px-2 text-gray-500 font-semibold" href="{% url 'login' %}">Login</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </nav>
        {% block body %}{% endblock %}
    </body>
</html>

users/templates/users/edit.html
{% extends 'users/base.html' %}
{% load static %}
{% block title %}
  Edit   
{% endblock %} 
{% block body %}
  {% static 'users/images/img_1_sq.jpg' as default_image %}
<div class="flex items-center mx-5 my-5">
  <img class="h-10 w-10 rounded-full" src="{% if request.user.profile.photo %}{{ request.user.profile.photo.url }}{% else %}{{ default_image }}{% endif %}" alt="User Profile Photo" onerror="this.onerror=null; this.src('{{ default_image }}')">
  <div class="ml-2">
    <h2 class="text-xl font-bold text-indigo-500">Edit {{ request.user.username }}'s Profile</h2>
    <p class="text-sm text-indigo-500"><a href="{% url 'password_change' %}">Change Password</a></p>
  </div>
</div>
<div class="container py-5 mx-10">
<form method="post" class="bg-white shadow-md m-10 px-8 rounded pt-6 pb-8 mb-4 w-4/5" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="mb-2">
    <label class="block text-grey-700 text-sm font-bold mb-2" for="">Username</label>
    <div class="shadow appearance-none border rounded py-2 px-3 mr-10 text-grey-700">
      {{ user_form.username }}
    </div>
  </div>
  <div class="mb-2">
    <label class="block text-grey-700 text-sm font-bold mb-2" for="">First Name</label>
    <div class="shadow appearance-none border rounded py-2 px-3 mr-10 text-grey-700">
      {{ user_form.first_name }}
    </div>
  </div>
  <div class="mb-2">
    <label class="block text-grey-700 text-sm font-bold mb-2" for="">Last Name</label>
    <div class="shadow appearance-none border rounded py-2 px-3 mr-10 text-grey-700">
      {{ user_form.last_name }}
    </div>
  </div>
  <div class="mb-2">
    <label class="block text-grey-700 text-sm font-bold mb-2" for="">Email</label>
    <div class="shadow appearance-none border rounded py-2 px-3 mr-10 text-grey-700">
      {{ user_form.email }}
    </div>
  </div>
  <div class="mb-2">
    <label class="block text-grey-700 text-sm font-bold mb-2" for="">Photo</label>
    <div class="shadow appearance-none border rounded py-2 px-3 mr-10 text-grey-700">
      {{ profile_form.photo }}
    </div>
  </div>
  <button type="submit" class="bg-green-500 text-white my-5 px-5 py-2">Submit</button>
</form>
</div>
{% endblock %}

users/templates/users/follower_create.html
{% extends 'users/base.html' %}
{% block title %}
        Follow        
{% endblock %} 
{% block body %}
  <div class="container mx-auto px-4">
    <h1 class="text-2xl font-bold mb-4">List of Users you are follow</h1>
    <div class="overflow-y-auto max-h-80">
      <ul class="divide-y divide-gray-200">
        {% for user in users_with_profiles %}
          <li class="py-2">
            <div class="flex items-center">
              <div class="ml-2">
                <strong>{{ user.username }}</strong> - {{ user.profile.photo }}
                <!-- Hier könnten weitere Informationen angezeigt werden -->
              </div>
              {% if user != request.user %}
                {% if user in request.user.profile.follow.all %}
                  <form method="post" action="{% url 'friends_delete' user.id %}" class="ml-auto">
                    {% csrf_token %}
                    <button type="submit" class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded">Unfollow</button>
                  </form>
                {% else %}
                  <form method="post" action="{% url 'follower_create' user.id %}" class="ml-auto">
                    {% csrf_token %}
                    <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Follow User</button>
                  </form>
                {% endif %}
              {% endif %}
            </div>
          </li>
        {% endfor %}
      </ul>
    </div>
  </div>
{% endblock %}

users/templates/users/friends_list.html
{% extends "users/base.html" %}
{% load static %}
{% block title %}
     Friends List         
{% endblock %} 
{% block body %}
  <h2 class="text-3xl font-normal mb-2 text-gray-500 ml-2">Friends of {{ user.username }}</h2>
  {% if friendships %}
    <ul>
      {% for friendship in friendships %}
        <li class="user-container flex mx-5 my-5">
          <img class="h-10 w-10 rounded-full ml-2 mr-2" 
               src="{{ friendship.to_user.profile.photo.url }}" 
               alt="{{ friendship.to_user.username }}'s Profile Photo" 
               onerror="this.onerror=null; this.src='{% static 'users/images/user.png' %}'">
          {{ friendship.to_user.username }}  ({{ friendship.created_at|date:"F j, Y" }})
        </li>
      {% endfor %}
    </ul>
    <a href="{% url 'friends_create' user_id=request.user.id %}" class="btn btn-primary">Find Friends</a>
  {% else %}
    <p>Sorry, for now {{ user.username }} has no friends yet. Try to make connections to other users.</p>
    <a href="{% url 'friends_create' user_id=request.user.id %}" class="btn btn-primary">Find Friends</a>
  {% endif %}a
{% endblock %}

users/templates/users/logout.html
{% extends "users/base.html" %}
{% block title %}
     Logout           
{% endblock %} 
{% block body %}
<div class="container mx-auto py-10">
    <h1 class="text-2xl m-10">You have been logged out</h1>
    <div class="m-10">
        <p><a href="{% url 'login' %}" class="text-white bg-green-500 px-5 py-2">Login again</a></p>
        <p class="mt-5"><a href="{% url 'password_reset' %}" class="text-indigo-500">Forgot password? Click here to reset</a></p>
    </div>
</div>
{% endblock %}

users/templates/users/userspage.html
{% extends 'users/base.html' %}
{% load static %}
{% block body %}
{% comment %} <div class="flex items-center mx-5 my-5">
    <img class="h-10 w-10 rounded-full" src="{{ request.user.profile.photo.url }}" alt="User Profile Photo">
    <a class="text-xl ml-2 font-bold text-indigo-500" href="{% url 'edit' %}">
        <h3>Edit {{ request.user.username }}'s Profile</h3>
    </a>
</div> {% endcomment %}

<div class="m-10">
    <h2 class="text-2xl font-bold">Create a Post</h2>
    <div class="container py-5 mx-10">
        <form method="post" class="bg-white shadow-md m-10 px-8 rounded pt-6 pb-8 mb-4 w-4/5" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="mb-2">
                <label class="block text-grey-700 text-sm font-bold mb-2" for="title">Add Title</label>
                <div class="shadow appearance-none border rounded py-2 px-3 mr-10 text-grey-700">
                    {{ form.title }}
                </div>
            </div>
            <div class="mb-2">
                <label class="block text-grey-700 text-sm font-bold mb-2" for="image">Add Image</label>
                <div class="shadow appearance-none border rounded py-2 px-3 mr-10 text-grey-700">
                    {{ form.image }}
                </div>
            </div>
            <div class="mb-2">
                <label class="block text-grey-700 text-sm font-bold mb-2" for="caption">Add Text</label>
                <div class="shadow appearance-none border rounded py-2 px-3 mr-10 text-grey-700">
                    {{ form.caption }}
                </div>
            </div>
            <div class="text-red-500 text-sm">
                {% if form.errors %}
                    {{ form.errors }}
                {% endif %}
            </div>
            <button type="submit" class="bg-green-500 text-white my-5 px-5 py-2">Submit</button>
        </form>
    </div>
</div>

<div class="flex mt-5 p-10 justify-center">
    <h2 class="text-3xl font-normal mb-2 text-gray-500">My Posts</h2>
</div>

<div class="grid grid-cols-1 gap-6 mx-auto p-10 justify-center">
    <!-- Post loop -->
    {% for post in posts %}
    <div class="rounded overflow-hidden w-[470px] h-auto bg-white shadow-lg mb-6">
        <!-- Post content -->
        <div class="user-container flex mx-5 my-5">
            <img class="h-10 w-10 rounded-full ml-2" src="{{ post.user.profile.photo.url }}" alt="User Profile Photo">
            <div class="mx-2 my-2 font-bold">
                <span class="text-indigo-500">{{ post.user.username }}</span>
            </div>
        </div>
        <img src="{{ post.image.url }}" alt="Post Image" class="object-cover w-full h-60">
        <div class="px-6 py-4">
            <div class="font-bold text-xl mb-2">{{ post.title }}</div>
            <p class="text-gray-700 text-base">{{ post.caption }}</p>
            <!-- Edit button for each post -->
            <a href="{% url 'edit_post' post.id %}" class="bg-blue-500 text-white px-4 py-2 rounded mt-2">Edit Post</a>
        </div>
        <!-- Comments section -->
        <div class="px-6 py-4">
            <h3 class="text-lg font-bold">Comments</h3>
            {% for comment in post.comments.all %}
            <div class="mb-2">
                <span class="font-bold text-sm text-gray-700">{{ comment.posted_by }} on {{ comment.created }}</span>
                <p class="text-xs text-gray-600">{{ comment.body }}</p>
            </div>
            {% endfor %}
            <!-- Comment form for each post -->
            <form method="post" action="{% url 'comment_create_user' request.user.username %}" class="bg-white shadow-md mt-4 px-4 rounded pt-6 pb-2 mb-4">
                {% csrf_token %}
                <div class="flex mb-2">
                    <div class="w-full">
                        <input class="w-full h-24 p-2 border border-gray-300 rounded" id="id_body" name="body">{{ comment_form_user.body }}
                    </div>
                    <input type="hidden" name="post_id" value="{{ post.id }}">  <!-- Hidden input for post ID -->
                    <button class="bg-green-500 text-white px-5 ml-2" type="submit">Add Comment</button>
                </div>
                {% if comment_form_user.errors %}
                <ul class="text-red-500 text-sm">
                    {% for field in comment_form_user %}
                        {% if field.errors %}
                            {% for error in field.errors %}
                                <li>{{ error|escape }}</li>
                            {% endfor %}
                        {% endif %}
                    {% endfor %}
                </ul>
                {% endif %}
            </form>
        </div>
    </div>
    {% endfor %}
</div>



{% endblock %}